//product Reducer types
export const SET_SALES_EMAIL = "SET_SALES_EMAIL";
export const SET_SALES_PHONE = "SET_SALES_PHONE";
export const SET_MARKETING_EMAIL = "SET_MARKETING_EMAIL";
export const SET_MARKETING_PHONE = "SET_MARKETING_PHONE";